travis:
  secure:
    BINSTAR_TOKEN: TbTctyal8lnBdnN5z+69l83fkYYAygC689OiTYXnHbTguW7wnUbNGUYaRtdQm0zvKTCUYFnV1GvJXvCwwg395BfbctCu9RPdjt07zon1hM9R/UNeWMZJt+1mD9i2nYjd4zX3JQKVmDuNXEYEd+1BbVYHGixCzKm5wReBJ6BgXabwnlG85rYKw05Ps6TMfOvn1GbpQPNF7O3uZiXWfSBkERWQtWjSplSs6UFKFAkqZBBs6DaypRG02m2maz+y5zZaz6qqY40IEpVGNkKQumvOMJWq+H5RE5mcsD4dHdWMnvQiySfVSHZ8ZYNoboosFInv5hebzeJHzw3OWfubC0rl1JUIFT2+Dr8f096CJtiCIukxtdWHJ8CcpkkIwB9Bx5x/pNK/pNZ930x+NVA0FClqdsMOrJM1BIj2sMvXZ8XoDluTlT6uyL580zpe4SbY3itBTiKSgE7IP2J/X5z39hW2sqEV6/DfnFV38x+VarfmI2yKSzlpsglpSpPAvE5fbK+rvD7uRb6Jgd1/Pa6PaCnKxctGbLvzFtBnTvPIdD7sF2sorDYcAo82V+LU8D0q1hqmQMBdYB4MijPpuuJ8FXkGiw5hWAEZXfX8Ic45g/C5xorySs+ex2yIYRbwgNvRHbqtE6itZFqKSjZdU7zjpTN4y4wo0U/Kj4E8O3p1KSRTmZo=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
