travis:
  secure:
    BINSTAR_TOKEN: dMGnu/XLX7C63/nU/WOK0pHbQMqcJ2pe2Fms9bHmndu/QWrUspcYCFd0wHuHV6idgCmK0wyu5WfDDN7VXKZUPlAckqSq7PMpxgYdAZA6GZDcxatD2roBBfMhy+JpgaGYtOLAj7/DVbh1sUOgJ4OuhNvlrusol2ZeAW72mBFvuh6Magdf3ISEMuXIdDs+M6vvU+NZv3z8nRhmTlqKUOxmrggrXOOBkAknfO5ZTn6aZjr+Qgk+MS9l9YrOdyN37C1a7cUR6bp+tdIATYl/zITdsMP+HdXdMO/11VZXCyQBfLZLg8zzlg/8JnYEm7vEMPZkeyIbEm4QHZW6Cz1qhHiqgzYLe6mYTD+oowQrYt6pv2/OLRDjh5/nm3JqtAwbDprvjbmkyRDG8TxWF/7J5GTGrDjNl9BPBvKk4jWgXqMXhB7glS7QFd5F2UEss0YQVmG2cH4VCvwYUZuVahXeFytcVMECNdG4qG6rdOMaw7pJXenCzc6dFIKN7fXPBZ0Y+GFMs7/WskvqhNjFiX7l1A07I+4MNgvOjQn1aSd8ukg0Xpqd1KSMKb2A5YlhzXajxLlC5dySm85FjNu2Ub4bTqlQCKyFv27ewaYXisHefebyQwFhN7vZ5YQnGsEyonG4IOMEBqjQM3JVZyiIEvAfiwTVACABjGYawm/0dx1YRyFDDtg=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
