travis:
  secure:
    BINSTAR_TOKEN: AOib9DprYHu2GcGYTjUMiX9dL/lBafDANG+r/IDT+G+QmRapS91eeyoSYdUGysiLwl46mCB2oDQSLpoxOtSc8+jGqgRbxh+QXrYbYgB14BmM5NSMlkIqV8IMcO5pnPa8LRv57p/sB9r5MaA6u1/DKA9lTFZ3w+ty6MxPHsdaB4eSgGSyFHoZVBaomp+R+J+O6qvrbkXS7eHoeQd/xir6FvUgI+qdB3NYorsx7Gkt9CvNg9n30XRHqyFfp0sxrkHB4Z0nzV6QY/qrz2gcnUAUZCNkWpuUkZpDKrELDSm9bZ/jacTmYWayrEYiZAUSELLDS4yKyhFZavNZfoMkLaHKCx3+4MHOqSHyQUiTKWjCedcylRAjLKpSljoMNlXjb1njBFYzi7ZyIqOO0q2ApKiI7sJBTzxDl3WZONc1Tm+TBjhSXVEav0tbDXPRzdVtMCn28LKt5wxzfvSc9M+7UoHcJc9+OI0RLNDtNpQno5rgc2TwifG9xCjcBDNOPA6/P9cef+t85Zfa0bQaLk8s+06Q2ihNoz+mmWLLkufiVWEZZkuY5lIQo4HMK3/eJk1gj2M2I3K/z8TysIJGccxCb5QM+FaQm8AhHmrWEAIc5Fl2vAhoXWBjIjwwd2y7+Sq/jMuKAY8kM1C18tlRPbdMzvnQHJh5TdU0fEvT+TmXWvy0LUE=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
